use uuid for generated task ids
neckhair/gcron pull request #18
Opened 2017-10-07 16:30 UTC by kai5263499

This is a small change to use a uuid for the task id instead of a random generator. I'm not sure if its more performant but it should provide a better assurance that the id generated would be unique. This will help if we want to emit task details for reporting purposes later.

2017-10-08 11:01 UTC, neckhair requested changes
Thanks for this PR. That's a good idea. Don't worry about performance. It's only loaded once on startup. That shouldn't have any impact.
CI seems to be broken. I'll try to fix that now.

2017-10-08 11:01 UTC, neckhair commented on crontainer/task.go
>  	log.Printf("[%15s] %s", t.Name, text)
Could you shorten this to 8 characters? That would be the first character block before the hyphen. For the output that should be enough.
```go
t.Name[:8]
```

2017-10-08 11:01 UTC, neckhair commented on crontainer/task.go
> +		name = uuid.NewV4()
This will not work. `name` is a `string`, but `New4()` returns a `UUID`. You can write `uuid.NewV4().String()`.

2017-10-08 11:12 UTC, neckhair commented
`.travis.yml` should be fixed now. Could you rebase your branch on master?

2017-10-08 22:15 UTC, kai5263499 commented
Thanks for the feedback! I've rebased onto your master branch, used the .String() method of uuid, and cut the characters down to 8

2017-10-10 11:16 UTC, neckhair approved these changes

2017-10-10 11:16 UTC, merged